### ISSUE TITLE
Can the code be converted to utf-8? I'll translate it into Thai.

### ISSUE THREAD

**Issue by watchakorn-18k** [Sergeanur/GXT#1]

**Comment by Sergeanur** [comment]
Yes

**Comment by watchakorn-18k** [comment]
I don't have a visual studio program, can you compiler for me? Or can you explain it in video? thank you

**Comment by Sergeanur** [comment]
You can make a charset table for a 2.0 version of the compiler: https://github.com/Sergeanur/GXT-compiler
