### ISSUE TITLE
GXT Decompiler

### ISSUE THREAD

**Issue by enrospv** [Sergeanur/GXT#2]
I was working on some translation but I lost the .txt file. I was wondering if you could help me with decompiling the .gxt I have so I can keep working on it.

This is the .gxt file: https://drive.google.com/file/d/1I7XB_4qz8xqj8aqH2g3odah4dBoSRJJd/view?usp=sharing

I don't think it there is any way to do this on my end but I looked for it and couldn't find it. Sorry if there is one. 

Thanks for your help.

**Comment by Sergeanur** [comment]
GXT now can be decompiled with this: https://github.com/Sergeanur/GXT-compiler
